name: pull request into main

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  internal-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Config nuget
      run: >
        dotnet nuget add source "https://nuget.pkg.github.com/floatingman-ltd/index.json" 
        --name "GITHUB"
        --username waltiam 
        --password ${{ secrets.GITHUB_TOKEN }} 
        --store-password-in-clear-text

    - name: Setup Gitversion
      uses: dotnet/nbgv@master
      id: nbgv

    - run: echo `SemVer2 = ${{ steps.nbgv.outputs.SemVer2 }}`

    # - name: Pack Nuget Package
    #   run: >
    #     dotnet pack Versioner/Versioner.csproj --configuration Debug 
    #     /p:AssemblyVersion='${{ steps.nbgv.outputs.AssemblyVersion }}' 
    #     /p:FileVersion='${{ steps.nbgv.outputs.AssemblyFileVersion }}' 
    #     /p:InformationalVersion='${{ steps.nbgv.outputs.NuGetPackageVersion }}' 
    #     /p:Version='${{ steps.nbgv.outputs.NuGetPackageVersion }}'

    - name: Pack Nuget Package
      run: >
        dotnet pack Versioner/Versioner.csproj --configuration Debug 
        /p:AssemblyVersion='0.0.1' 
        /p:FileVersion='0.0.1' 
        /p:InformationalVersion='${{ steps.nbgv.outputs.NuGetPackageVersion }}' 
        /p:Version='${{ steps.nbgv.outputs.NuGetPackageVersion }}'

    - name: Publish nuget to Github -> this works
      run: >
        dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} 
        --source "https://nuget.pkg.github.com/waltiam/index.json"


    - name: Publish nuget to Github -> this fails
      run: >
        dotnet nuget push **/*.nupkg 
        --api-key ${{ secrets.GITHUB_TOKEN }} 
        --source "GITHUB"