name: pull request into main

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  internal-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Config nuget
      run: >
        dotnet nuget add source "https://nuget.pkg.github.com/floatingman-ltd/index.json" 
        --name "GITHUB"
        --username waltiam 
        --password ${{ secrets.GITHUB_TOKEN }} 
        --store-password-in-clear-text

    - name: Setup Gitversion
      uses: dotnet/nbgv@master
      id: nbgv

    - run: echo 'SemVer2 = ${{ steps.nbgv.outputs.SemVer2 }}'

    - name: Pack Nuget Package
      run: >
        dotnet pack Versioner/Versioner.csproj --configuration Debug 
        /p:AssemblyVersion='${{ steps.nbgv.outputs.assemblySemVer }}' 
        /p:FileVersion='${{ steps.nbgv.outputs.assemblySemFileVer }}' 
        /p:InformationalVersion='${{ steps.nbgv.outputs.nuGetVersion }}' 
        /p:Version='${{ steps.nbgv.outputs.nuGetVersion }}'

    - name: Publish nuget to Github
      run: >
        dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} 
        --source "https://nuget.pkg.github.com/waltiam/index.json"