name: push into main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  nuget-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Gitversion
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Pack Nuget Package
      run: >
        dotnet pack Versioner/Versioner.csproj --configuration Release 
        /p:AssemblyVersion='${{ steps.nbgv.outputs.assemblySemVer }}' 
        /p:FileVersion='${{ steps.nbgv.outputs.assemblySemFileVer }}' 
        /p:InformationalVersion='${{ steps.nbgv.outputs.nuGetVersion }}' 
        /p:Version='${{ steps.nbgv.outputs.nuGetVersion }}'

    - name: Publish nuget to Github
      run: >
        dotnet nuget push **/*.nupkg 
        --api-key ${{ secrets.NUGET_API_KEY }} 
        --source "nuget.org"
