name: Release

on:
  workflow_dispatch:
  push:
    branches:
      [release/v*]

jobs:

  nuget-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Gitversion
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Pack Nuget Package
      run: >
        dotnet pack Versioner/Versioner.csproj --configuration Release 
        /p:AssemblyVersion='${{ steps.nbgv.outputs.assemblySemVer }}' 
        /p:FileVersion='${{ steps.nbgv.outputs.assemblySemFileVer }}' 
        /p:InformationalVersion='${{ steps.nbgv.outputs.nuGetVersion }}' 
        /p:Version='${{ steps.nbgv.outputs.nuGetVersion }}'

    # - name: Publish nuget to Github
    #   run: >
    #     dotnet nuget push **/*.nupkg 
    #     --api-key ${{ secrets.NUGET_API_KEY }} 
    #     --source "nuget.org"
    #     

    - name: Display GitVersion outputs
      run: |
        echo "CloudBuildNumber: ${{ steps.nbgv.outputs.CloudBuildNumber }}"
        echo "VersionFileFound: ${{ steps.nbgv.outputs.VersionFileFound }}"
        echo "AssemblyVersion: ${{ steps.nbgv.outputs.AssemblyVersion }}"
        echo "AssemblyFileVersion: ${{ steps.nbgv.outputs.AssemblyFileVersion }}"
        echo "AssemblyInformationalVersion: ${{ steps.nbgv.outputs.AssemblyInformationalVersion }}"
        echo "PublicRelease: ${{ steps.nbgv.outputs.PublicRelease }}"
        echo "PrereleaseVersion: ${{ steps.nbgv.outputs.PrereleaseVersion }}"
        echo "PrereleaseVersionNoLeadingHyphen: ${{ steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen }}"
        echo "SimpleVersion: ${{ steps.nbgv.outputs.SimpleVersion }}"
        echo "BuildNumber: ${{ steps.nbgv.outputs.BuildNumber }}"
        echo "VersionRevision: ${{ steps.nbgv.outputs.VersionRevision }}"
        echo "MajorMinorVersion: ${{ steps.nbgv.outputs.MajorMinorVersion }}"
        echo "VersionMajor: ${{ steps.nbgv.outputs.VersionMajor }}"
        echo "VersionMinor: ${{ steps.nbgv.outputs.VersionMinor }}"
        echo "GitCommitId: ${{ steps.nbgv.outputs.GitCommitId }}"
        echo "GitCommitIdShort: ${{ steps.nbgv.outputs.GitCommitIdShort }}"
        echo "GitCommitDate: ${{ steps.nbgv.outputs.GitCommitDate }}"
        echo "VersionHeight: ${{ steps.nbgv.outputs.VersionHeight }}"
        echo "VersionHeightOffset: ${{ steps.nbgv.outputs.VersionHeightOffset }}"
        echo "Version: ${{ steps.nbgv.outputs.Version }}"
        echo "BuildMetadataFragment: ${{ steps.nbgv.outputs.BuildMetadataFragment }}"
        echo "NuGetPackageVersion: ${{ steps.nbgv.outputs.NuGetPackageVersion }}"
        echo "ChocolateyPackageVersion: ${{ steps.nbgv.outputs.ChocolateyPackageVersion }}"
        echo "NpmPackageVersion: ${{ steps.nbgv.outputs.NpmPackageVersion }}"
        echo "SemVer1: ${{ steps.nbgv.outputs.SemVer1 }}"
        echo "SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}"
