name: push to any

on:
  workflow_dispatch:
  push:
    branches-ignore:
      [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400

    - name: Install dependencies
      run: dotnet restore

    - name: Setup Gitversion
      uses: dotnet/nbgv@master
      id: nbgv
      with:
        stamp: version.json

    - name: Display GitVersion outputs
      run: |
        echo "CloudBuildNumber: ${{ steps.nbgv.outputs.CloudBuildNumber }}"
        echo "VersionFIleFound: ${{ steps.nbgv.outputs.VersionFIleFound }}"
        echo "AssemblyVersion: ${{ steps.nbgv.outputs.AssemblyVersion }}"
        echo "AssemblyFileVersion: ${{ steps.nbgv.outputs.AssemblyFileVersion }}"
        echo "AssemblyInformationalVersion: ${{ steps.nbgv.outputs.AssemblyInformationalVersion }}"
        echo "PublicRelease: ${{ steps.nbgv.outputs.PublicRelease }}"
        echo "PrereleaseVersion: ${{ steps.nbgv.outputs.PrereleaseVersion }}"
        echo "PrereleaseVersionNoLeadingHyphen: ${{ steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen }}"
        echo "SimpleVersion: ${{ steps.nbgv.outputs.SimpleVersion }}"
        echo "BuildNumber: ${{ steps.nbgv.outputs.BuildNumber }}"
        echo "VersionRevision: ${{ steps.nbgv.outputs.VersionRevision }}"
        echo "MajorMinorVersion: ${{ steps.nbgv.outputs.MajorMinorVersion }}"
        echo "VersionMajor: ${{ steps.nbgv.outputs.VersionMajor }}"
        echo "VersionMinor: ${{ steps.nbgv.outputs.VersionMinor }}"
        echo "GitCommitId: ${{ steps.nbgv.outputs.GitCommitId }}"
        echo "GitCommitIdShort: ${{ steps.nbgv.outputs.GitCommitIdShort }}"
        echo "GitCommitDate: ${{ steps.nbgv.outputs.GitCommitDate }}"
        echo "VersionHeight: ${{ steps.nbgv.outputs.VersionHeight }}"
        echo "VersionHeightOffset: ${{ steps.nbgv.outputs.VersionHeightOffset }}"
        echo "Version: ${{ steps.nbgv.outputs.Version }}"
        echo "BuildMetadataFragment: ${{ steps.nbgv.outputs.BuildMetadataFragment }}"
        echo "NuGetPackageVersion: ${{ steps.nbgv.outputs.NuGetPackageVersion }}"
        echo "ChocolateyPackageVersion: ${{ steps.nbgv.outputs.ChocolateyPackageVersion }}"
        echo "NpmPackageVersion: ${{ steps.nbgv.outputs.NpmPackageVersion }}"
        echo "SemVer1: ${{ steps.nbgv.outputs.SemVer1 }}"
        echo "SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}"